version: "3"
services:
  web:
    restart: always
    image: ${TestDataFactory_IMAGE}
    container_name: TestDataFactory_web
    env_file:
      - ./TestDataFactory.env
    volumes:
      - ./web/static:/opt/cloud/TestDataFactory/static
    networks:
      - backend
      - frontend

  nginx:
    restart: always
    image: ${NGINX_IMAGE}
    container_name: TestDataFactory_nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./web/static:/usr/share/nginx/TestDataFactory/static
    ports:
      - "${NGINX_PORT}:80"
    links:
      - web
    networks:
      - frontend

networks:
  backend:
    driver: bridge
  frontend:
    driver: bridge
